### ISSUE TITLE
What is the license type?

### ISSUE THREAD

**Issue by sghose-ttc** [OneHQ/sendgrid_webapi#9]
Didn't see a license file for this gem. Would you be willing to add a license file?

**Comment by Skipants** [comment]
@dnnyjns Thanks for the gem 🍻!! If you're able to address the lack-of-license that would be great. Due to pressure from the suits I'll have to remove the gem from our app and make some refactors of our sendgrid stuff otherwise.

**Comment by dnnyjns** [comment]
> @dnnyjns Thanks for the gem 🍻!! If you're able to address the lack-of-license that would be great. Due to pressure from the suits I'll have to remove the gem from our app and make some refactors of our sendgrid stuff otherwise.

On it :)

**Comment by dnnyjns** [comment]
> @dnnyjns Thanks for the gem 🍻!! If you're able to address the lack-of-license that would be great. Due to pressure from the suits I'll have to remove the gem from our app and make some refactors of our sendgrid stuff otherwise.

v0.1.2 has been published with the MIT license

**Comment by Skipants** [comment]
Thanks! You're my hero!
